name: website

on:
  release:
    types: [published]
  pull_request:
    branches:
      - main
  push:
    branches:
      - main
  workflow_dispatch:
    inputs:
      deploy:
        description: Deploy website
        required: false
        default: true
        type: boolean

jobs:
  build-react-animotion:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: pnpm/action-setup@v2
        with:
          version: 8.6.2
      - uses: actions/setup-node@v3
        with:
          node-version: 18.16
          cache: pnpm
      - run: pnpm install --frozen-lockfile
      - run: pnpm run rollup
      - uses: actions/upload-artifact@v3
        with:
          name: rdp-dist
          path: website/dist

  build-website:
    needs: [build-react-animotion]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: pnpm/action-setup@v2
        with:
          version: 8.6.2
      - uses: actions/setup-node@v3
        with:
          node-version: 18.16
          cache: pnpm
      - uses: actions/download-artifact@v3
        with:
          name: rdp-dist
          path: dist
      - run: pnpm install --frozen-lockfile
      - run: pnpm -F website build
      - uses: actions/upload-artifact@v3
        with:
          name: website-build
          path: website/dist

  deploy:
    runs-on: ubuntu-latest
    needs: [build-website]
    if: ${{ github.event_name == 'release' || github.event.inputs.deploy }}
    steps:
      - uses: actions/checkout@v3
      - uses: pnpm/action-setup@v2
        with:
          version: 8.6.2
      - uses: actions/setup-node@v3
        with:
          node-version: 18.16
          registry-url: https://registry.npmjs.org/
      - uses: actions/download-artifact@v3
        with:
          name: website-build
          path: website/dist
      - uses: actions/download-artifact@v3
        with:
          name: rdp-dist
          path: website/dist
      - run: pnpm install --frozen-lockfile
      - uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: website/dist